/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ICClose: typeof import('~icons/c/close')['default']
    ICMaximize: typeof import('~icons/c/maximize')['default']
    ICMinimize: typeof import('~icons/c/minimize')['default']
    TitleBar: typeof import('./src/renderer/src/components/TitleBar.vue')['default']
    Versions: typeof import('./src/renderer/src/components/Versions.vue')['default']
  }
}
